[package]
name = "flow"
version = "0.1.0"
edition = "2021"

[dependencies]
datatypes = { path = "../datatypes" }
parser = { path = "../parser" }
serde_json = "1.0"
arrow = { version = "56.2", default-features = false }
datafusion = "50"
datafusion-common = "50"
datafusion-expr = "50"
sqlparser = { version = "0.40", features = ["serde", "visitor"] }
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
futures = "0.3"
thiserror = "1.0"
