[workspace]
members = [
    "src/flow",
    "src/datatypes",
]
resolver = "2"

[package]
name = "rs-flow-demo"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "rs-flow-demo"
path = "src/main.rs"
