[workspace]
members = [
    "src/flow",
    "src/datatypes",
    "src/parser", "src/manager",
    "src/telemetry",
]
resolver = "2"

[package]
name = "synapse-flow"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", default-features = false, features = ["macros", "rt-multi-thread", "sync", "time", "signal"] }
prometheus_exporter = "0.8"
sysinfo = "0.30"
pprof = { version = "0.6.1", features = ["flamegraph", "protobuf"] }
tikv-jemallocator = { version = "0.6.0", features = ["profiling"] }
tikv-jemalloc-ctl = { version = "0.6.0", features = ["stats"] }
manager = { path = "src/manager" }
telemetry = { path = "src/telemetry" }

[[bin]]
name = "synapse-flow"
path = "src/main.rs"

[profile.release-min]
inherits = "release"
opt-level = "z"
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"
