[workspace]
members = [
    "src/flow",
    "src/datatypes",
    "src/parser", "src/manager",
    "src/telemetry", "src/storage",
]
resolver = "2"

[package]
name = "synapse-flow"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", default-features = false, features = ["macros", "rt-multi-thread", "sync", "time", "signal"] }
prometheus_exporter = { version = "0.8", optional = true }
sysinfo = { version = "0.30", optional = true }
pprof = { version = "0.6.1", features = ["flamegraph", "protobuf"], optional = true }
tikv-jemallocator = { version = "0.6.0", features = ["profiling"], optional = true }
tikv-jemalloc-ctl = { version = "0.6.0", features = ["stats"], optional = true }
manager = { path = "src/manager" }
flow = { path = "src/flow" }
telemetry = { path = "src/telemetry", optional = true }
storage = { path = "src/storage" }

[features]
default = ["metrics", "profiling"]
metrics = ["dep:prometheus_exporter", "dep:sysinfo", "telemetry"]
profiling = ["dep:pprof", "dep:tikv-jemallocator", "dep:tikv-jemalloc-ctl"]

[[bin]]
name = "synapse-flow"
path = "src/main.rs"

[profile.release-thin]
inherits = "release"
opt-level = 2
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"
