[package]
name = "parser"
version = "0.0.1"
edition = "2024"

[dependencies]
sqlparser = { version = "0.40", features = ["serde", "visitor"] }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"
