name: Deadlock Static Analysis

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  lockbud-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src

      - name: Cache Lockbud
        id: cache-lockbud
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/lockbud
          key: ${{ runner.os }}-lockbud

      - name: Install Lockbud
        if: steps.cache-lockbud.outputs.cache-hit != 'true'
        run: cargo install lockbud

      - name: Run Lockbud Analysis
        run: |
          lockbud analyze